# -*- coding: utf-8 -*-
"""
Created on Thu Nov 21 15:38:43 2019

@author: Mijael
"""

vnclass_dict = {
'stop-55.4':                  ['causer', 'theme', 'location'],
'masquerade-29.6':            ['agent', 'attribute', 'location'],
'masquerade-29.6-1':          ['agent', 'attribute', 'location'],
'masquerade-29.6-2':          ['agent', 'attribute', 'location'],
'captain-29.8':               ['agent', 'beneficiary', 'location'],
'captain-29.8-1':             ['agent', 'beneficiary', 'location'],
'captain-29.8-1-1':           ['agent', 'beneficiary', 'location'],
'preparing-26.3':             ['agent', 'product', 'material', 'beneficiary', 'location'],
'defend-72.3':                ['agent', 'beneficiary', 'theme', 'location'],
'help-72.1':                  ['agent', 'beneficiary', 'theme', 'location'],
'help-72.1-1':                ['agent', 'beneficiary', 'theme', 'location'],
'help-72.1-1-1':              ['agent', 'beneficiary', 'theme', 'location'],
'help-72.1-2':                ['agent', 'beneficiary', 'theme', 'location'],
'interact-36.6':              ['agent', 'co_agent', 'location'],
'marry-36.2':                 ['agent', 'co_agent', 'location'],
'meet-36.3':                  ['agent', 'co_agent', 'location'],
'meet-36.3-1':                ['agent', 'co_agent', 'location'],
'meet-36.3-2':                ['agent', 'co_agent', 'location'],
'subordinate-95.2.1':         ['agent', 'co_agent', 'location'],
'supervision-95.2.2':         ['agent', 'co_agent', 'location'],
'cooperate-73.1':             ['agent', 'co_agent', 'theme', 'location'],
'cooperate-73.1-1':           ['agent', 'co_agent', 'theme', 'location'],
'cooperate-73.1-2':           ['agent', 'co_agent', 'theme', 'location'],
'cooperate-73.1-3':           ['agent', 'co_agent', 'theme', 'location'],
'correspond-36.1.1':          ['agent', 'co_agent', 'topic', 'location'],
'correspond-36.1.1-1':        ['agent', 'co_agent', 'topic', 'location'],
'correspond-36.1.1-1-1':      ['agent', 'co_agent', 'topic', 'location'],
'conspire-71':                ['agent', 'co_agent', ['theme', 'beneficiary'], 'location'],
'battle-36.4':                ['agent', 'co_agent', ['theme', 'topic'], ['location']],
'battle-36.4-1':              ['agent', 'co_agent', ['theme', 'topic'], ['location']],
'settle-36.1.2':              ['agent', 'co_agent', ['topic', 'goal'], 'location'],
'settle-36.1.2-1':            ['agent', 'co_agent', ['topic', 'goal'], 'location'],
'butter-9.9':                 ['agent', 'destination', 'theme', 'initial_location', 'trajectory', 'location'],
'fill-9.8':                   ['agent', 'destination', 'theme', 'initial_location', 'trajectory', 'location'],
'fill-9.8-1':                 ['agent', 'destination', 'theme', 'initial_location', 'trajectory', 'location'],
'spend_time-104':             ['agent', 'duration', 'attribute', 'location'],
'touch-20':                   ['agent', 'theme', 'experiencer', 'instrument', 'location'],
'touch-20-1':                 ['agent', 'theme', 'experiencer', 'instrument', 'location'],
'assuming_position-50':       ['agent', 'location'],
'gobble-39.3':                ['agent', 'patient', 'location'],
'hiccup-40.1.1':              ['agent', 'location'],
'snooze-40.4':                ['agent', 'location'],
'concealment-16':             ['agent', 'patient', 'beneficiary', 'location'],
'concealment-16-1':           ['agent', 'patient', 'beneficiary', 'location'],
#'tape-22.4-1':                ['agent', 'patient', 'co_patient', 'instrument', 'location'],
'hit-18.1':                   ['agent', 'patient', 'co_patient', 'instrument', 'result', 'location'],
'tape-22.4':                  ['agent', 'patient', 'co_patient', 'instrument', 'result', 'location'],
'amalgamate-22.2':            ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-1':          ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-1-1':        ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-2':          ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-2-1':        ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-3':          ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-3-1':        ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-3-1-1':      ['agent', 'patient', 'co_patient', 'location'],
'amalgamate-22.2-3-2':        ['agent', 'patient', 'co_patient', 'location'],
'disassemble-23.3':           ['agent', 'patient', 'co_patient', 'location'],
'mix-22.1':                   ['agent', 'patient', 'co_patient', 'location'],
'mix-22.1-1':                 ['agent', 'patient', 'co_patient', 'location'],
'mix-22.1-1-1':               ['agent', 'patient', 'co_patient', 'location'],
'mix-22.1-2':                 ['agent', 'patient', 'co_patient', 'location'],
'mix-22.1-2-1':               ['agent', 'patient', 'co_patient', 'location'],
'separate-23.1':              ['agent', 'patient', 'co_patient', 'location'],
'separate-23.1-1':            ['agent', 'patient', 'co_patient', 'location'],
'separate-23.1-2':            ['agent', 'patient', 'co_patient', 'location'],
'shake-22.3':                 ['agent', 'patient', 'co_patient', 'location'],
'shake-22.3-1':               ['agent', 'patient', 'co_patient', 'location'],
'shake-22.3-1-1':             ['agent', 'patient', 'co_patient', 'location'],
'shake-22.3-2':               ['agent', 'patient', 'co_patient', 'location'],
'shake-22.3-2-1':             ['agent', 'patient', 'co_patient', 'location'],
'split-23.2':                 ['agent', 'patient', 'co_patient', 'location'],
'adjust-26.9':                ['agent', 'patient', 'goal', 'source', 'location'],
'swat-18.2':                  ['agent', 'patient', 'instrument',  'result', 'location'],
'bend-45.2':                  ['agent', 'patient', 'instrument', 'location'],
'carve-21.2':                 ['agent', 'patient', 'instrument', 'location'],
'carve-21.2-1':               ['agent', 'patient', 'instrument', 'location'],
'carve-21.2-2':               ['agent', 'patient', 'instrument', 'location'],
'cooking-45.3':               ['agent', 'patient', 'instrument', 'location'],
'cut-21.1-1':                 [['agent', 'causer'], 'patient', 'experiencer', 'instrument', 'movement', 'location'],
'destroy-44':                 ['agent', 'patient', 'instrument', 'location'],
'floss-41.2.1':               ['agent', 'patient', 'instrument', 'final_state', 'location'],
'hit-18.1-1':                 ['agent', 'patient', 'instrument', 'location'],
'murder-42.1':                ['agent', 'patient', 'instrument', 'location'],
'murder-42.1-1':              ['agent', 'patient', 'instrument', 'location'],
'other_cos-45.4':             ['agent', 'patient', 'instrument', 'result', 'final_state', 'location'],
'remedy-45.7':                ['agent', 'patient', 'instrument', 'result', 'final_state', 'location'],
'remedy-45.7-1':              ['agent', 'patient', 'instrument', 'result', 'final_state', 'location'],
'subjugate-42.3':             ['agent', 'patient', 'instrument', 'location'],
'break-45.1':                 ['agent', 'patient', 'instrument', 'result', 'final_state',  'location'],
'poison-42.2':                ['agent', 'patient', 'instrument', 'result', 'location'],
'spank-18.3':                 ['agent', 'patient', 'instrument', 'result', 'location'],
'cut-21.1':                   ['agent', 'patient', 'instrument', 'source', ['goal', 'result'], 'movement', 'location'],
'attack-60.1':                ['agent', 'patient', 'location'],
'attack-60.1-1':              ['agent', 'patient', 'location'],
'birth-28.2':                 ['agent', 'patient', 'location'],
'birth-28.2-1':               ['agent', 'patient', 'location'],
'body_internal_motion-49.1':  ['agent', 'patient', 'location'],
'braid-41.2.2':               ['agent', 'patient', 'final_state', 'location'],
'calve-28.1':                 ['agent', 'patient', 'location'],
'chew-39.2':                  ['agent', 'patient', 'location'],
'chew-39.2-1':                ['agent', 'patient', 'location'],
'chew-39.2-2':                ['agent', 'patient', 'location'],
'dine-39.5':                  ['agent', 'patient', 'location'],
'dress-41.1.1':               ['agent', 'patient', 'location'],
'dressing_well-41.3.2':       [['agent', 'patient'], 'location'],
'eat-39.1-3':                 ['agent', 'patient', 'location'],
'gobble-39.3-1':              ['agent', 'patient', 'location'],
'gobble-39.3-2':              ['agent', 'patient', 'location'],
'gorge-39.6':                 ['agent', 'patient', 'location'],
'groom-41.1.2':               ['agent', 'patient', 'location'],
'urge-58.1':                  ['agent', 'patient', 'result', 'location'],
'void-106':                   ['agent', 'patient', 'result', 'location'],
'coloring-24':                ['agent', 'patient', 'material', 'result', 'location'],
'compel-59.1':                ['agent', 'patient', 'predicate', 'location'],
'lure-59.3':                  ['agent', 'patient', 'predicate', 'location'],
'stimulate-59.4':             ['agent', 'patient', 'predicate', 'location'],
'grow-26.2.1':                ['agent', 'patient', 'product', 'location'],
'rear-26.2.2':                ['agent', 'patient', 'product', 'location'],
'rear-26.2.2-1':              ['agent', 'patient', 'product', 'location'],
'turn-26.6.1':                ['agent', 'patient', 'result', 'initial_state', 'location'],
'turn-26.6.1-1':              ['agent', 'patient', 'result', 'initial_state', 'location'],
'beg-58.2':                   ['agent', 'patient', 'result', 'location'],
'beg-58.2-1':                 ['agent', 'patient', 'result', 'location'],
'beg-58.2-1-1':               ['agent', 'patient', 'result', 'location'],
'bully-59.5':                 ['agent', 'patient', 'result', 'location'],
'order-58.3':                 ['agent', 'patient', 'result', 'location'],
'order-58.3-1':               ['agent', 'patient', 'result', 'location'],
'other_cos-45.4-1':           ['agent', 'patient', 'result', 'location'],
'suffocate-40.7':             ['agent', 'patient', 'result', 'location'],
'render-29.90-1':             ['agent', 'patient', 'result', 'source', 'location'],
'render-29.90-2':             ['agent', 'patient', 'result', 'source', 'location'],
'devour-39.4':                ['agent', 'patient', 'source', 'location'],
'eat-39.1':                   ['agent', 'patient', 'source', 'location'],
'eat-39.1-1':                 ['agent', 'patient', 'source', 'location'],
'eat-39.1-2':                 ['agent', 'patient', 'source', 'location'],
'prosecute-33.2-1':           ['agent', 'patient', 'theme', 'attribute', 'location'],
'prosecute-33.2':             ['agent', 'patient', 'theme', 'location'],
'trick-59.2':                 ['agent', 'patient', ['predicate', 'result'], 'location'],
'convert-26.6.2-1-1':         ['agent', 'patient', ['result', 'goal'], 'initial_state', 'location'],
'urge-58.1-1':                ['agent', 'patient', ['topic', 'result'], 'location'],
'urge-58.1-1-1':              ['agent', 'patient', ['topic', 'result'], 'location'],
'act-114':                    ['agent', 'predicate', 'location'],
'act-114-1':                  ['agent', 'predicate', 'location'],
'act-114-1-1':                ['agent', 'predicate', 'location'],
'preparing-26.3-1':           ['agent', 'product', 'material', 'beneficiary', 'location'],
'preparing-26.3-2':           ['agent', 'product', 'material', 'beneficiary', 'location'],
'build-26.1':                 ['agent', 'product', 'material', 'asset', 'beneficiary', 'location'],
'build-26.1-1':               ['agent', 'product', 'material', 'asset', 'beneficiary', 'location'],
'knead-26.5':                 ['agent', 'product', 'material', 'location'],
'bill-54.5':                  ['agent', 'recipient', 'asset', 'location'],
'animal_sounds-38':           ['agent', 'recipient', 'theme', 'location'],
'create-26.4-1':              ['agent', 'result', 'beneficiary', 'location'],
'create-26.4':                ['agent', 'result', 'material', 'beneficiary', 'location'],
'create-26.4-1-1':            ['agent', 'result', 'material', 'beneficiary', 'location'],
'resign-10.11':               ['agent', 'source', 'goal', 'location'],
'resign-10.11-1':             ['agent', 'source', 'goal', 'location'],
'resign-10.11-2':             ['agent', 'source', 'goal', 'location'],
'withdraw-82':                ['agent', 'source', 'location'],
'withdraw-82-1':              ['agent', 'source', 'location'],
'withdraw-82-2':              ['agent', 'source', 'location'],
'withdraw-82-3':              ['agent', 'source', 'location'],
'substance_emission-43.4-1-1': ['agent', 'source', 'theme', 'location'],
'assessment-34.1':            ['agent', 'theme', 'attribute', 'location'],
'characterize-29.2':          ['agent', 'theme', 'attribute', 'location'],
'characterize-29.2-1':        ['agent', 'theme', 'attribute', 'location'],
'characterize-29.2-1-1':      ['agent', 'theme', 'attribute', 'location'],
'characterize-29.2-1-2':      ['agent', 'theme', 'attribute', 'location'],
'consider-29.9':              ['agent', 'theme', 'attribute', 'location'],
'consider-29.9-1':            ['agent', 'theme', 'attribute', 'location'],
'consider-29.9-1-1':          ['agent', 'theme', 'attribute', 'location'],
'consider-29.9-1-1-1':        ['agent', 'theme', 'attribute', 'location'],
'consider-29.9-2':            ['agent', 'theme', 'attribute', 'location'],
'hire-13.5.3':                ['agent', 'theme', 'attribute', 'location'],
'judgment-33.1':              ['agent', 'theme', 'attribute', 'location'],
'judgment-33.1-1':            ['agent', 'theme', 'attribute', 'location'],
'judgment-33.1-1-1':          ['agent', 'theme', 'attribute', 'location'],
'pronounce-29.3.1':           ['agent', 'theme', 'attribute', 'location'],
'suspect-81':                 ['agent', 'theme', 'attribute', 'location'],
'sustain-55.6-1':             ['agent', 'theme', 'attribute', 'location'],
'volunteer-95.4-1':           ['agent', 'theme', 'attribute', 'location'],
'register-54.1-1':            ['agent', 'theme', 'attribute', 'value', 'location'],
'allow-64.1':                 ['agent', 'theme', 'beneficiary', 'location'],
'allow-64.1-1':               ['agent', 'theme', 'beneficiary', 'location'],
'conduct-111.1':              ['agent', 'theme', 'beneficiary', 'location'],
'forbid-64.4':                ['agent', 'theme', 'beneficiary', 'location'],
'forbid-64.4-1':              ['agent', 'theme', 'beneficiary', 'location'],
'let-64.2':                   ['agent', 'theme', 'beneficiary', 'location'],
'performance-26.7':           ['agent', 'theme', 'beneficiary', 'location'],
'performance-26.7-1':         ['agent', 'theme', 'beneficiary', 'location'],
'employment-95.3':            ['agent', 'theme', 'co_agent', 'attribute', 'location'],
'play-114.2':                 ['agent', 'theme', 'co_agent', 'location'],
'play-114.2-1':               ['agent', 'theme', 'co_agent', 'location'],
'work-73.2':                  ['agent', 'theme', 'co_agent', 'location'],
'correlate-86.1':             ['agent', 'theme', 'co_theme', 'location'],
'herd-47.5.2':                ['agent', 'theme', 'co_theme', 'location'],
'multiply-108':               ['agent', 'theme', 'co_theme', 'location'],
'multiply-108-1':             ['agent', 'theme', 'co_theme', 'location'],
'multiply-108-2':             ['agent', 'theme', 'co_theme', 'location'],
'multiply-108-3':             ['agent', 'theme', 'co_theme', 'location'],
'carry-11.4':                 ['agent', 'theme', 'destination', 'initial_location', 'location'],
'carry-11.4-1':               ['agent', 'theme', 'destination', 'initial_location', 'location'],
'carry-11.4-1-1':             ['agent', 'theme', 'destination', 'initial_location', 'location'],
'coil-9.6':                   ['agent', 'theme', 'destination', 'initial_location', 'location'],
'confine-92':                 ['agent', 'theme', 'destination', 'initial_location', 'location'],
'confine-92-1':               ['agent', 'theme', 'destination', 'initial_location', 'location'],
'drive-11.5':                 ['agent', 'theme', 'destination', 'initial_location', 'location'],
'drive-11.5-1':               ['agent', 'theme', 'destination', 'initial_location', 'location'],
'funnel-9.3':                 ['agent', 'theme', 'destination', 'initial_location', 'location'],
'funnel-9.3-1':               ['agent', 'theme', 'destination', 'initial_location', 'location'],
'funnel-9.3-1-1':             ['agent', 'theme', 'destination', 'initial_location', 'location'],
'pelt-17.2':                  ['agent', 'theme', 'destination', 'initial_location', 'location'],
'pocket-9.10':                ['agent', 'theme', 'destination', 'initial_location', 'location'],
'pocket-9.10-1':              ['agent', 'theme', 'destination', 'initial_location', 'location'],
'put-9.1':                    ['agent', 'theme', 'destination', 'initial_location', 'location'],
'put-9.1-1':                  ['agent', 'theme', 'destination', 'initial_location', 'location'],
'put-9.1-2':                  ['agent', 'theme', 'destination', 'initial_location', 'location'],
'put_direction-9.4':          ['agent', 'theme', 'destination', 'initial_location', 'location'],
'put_spatial-9.2':            ['agent', 'theme', 'destination', 'initial_location', 'location'],
'send-11.1':                  ['agent', 'theme', 'destination', 'initial_location', 'location'],
'send-11.1-1':                ['agent', 'theme', 'destination', 'initial_location', 'location'],
'slide-11.2-1':               ['agent', 'theme', 'destination', 'initial_location', 'location'],
'spray-9.7':                  ['agent', 'theme', 'destination', 'initial_location', 'location'],
'spray-9.7-1':                ['agent', 'theme', 'destination', 'initial_location', 'location'],
'accompany-51.7':             ['agent', 'theme', 'destination', 'initial_location', 'trajectory', 'location'],
'nonvehicle-51.4.2':          ['agent', 'theme', 'destination', 'initial_location', 'trajectory', 'location'],
'run-51.3.2-2-1':             ['agent', 'theme', 'destination', 'initial_location', 'trajectory', 'location'],
'slide-11.2':                 ['agent', 'theme', 'destination', 'initial_location', 'trajectory', 'location'],
'illustrate-25.3':            ['agent', 'theme', 'destination', 'location'],
'image_impression-25.1':      ['agent', 'theme', 'destination', 'location'],
'scribble-25.2':              ['agent', 'theme', 'destination', 'location'],
'scribble-25.2-1':            ['agent', 'theme', 'destination', 'location'],
'spray-9.7-1-1':              ['agent', 'theme', 'destination', 'location'],
'spray-9.7-2':                ['agent', 'theme', 'destination', 'location'],
'transcribe-25.4':            ['agent', 'theme', 'destination', 'location'],
'pit-10.7':                   ['agent', 'theme', 'destination', 'source', 'location'],
'rotate-51.9.1-1':            ['agent', 'theme', 'extent', 'initial_location', 'location'],
'classify-29.10':             ['agent', 'theme', 'goal', 'location'],
'dedicate-79':                ['agent', 'theme', 'goal', 'location'],
'exclude-107.3':              ['agent', 'theme', 'goal', 'location'],
'exclude-107.3-1':            ['agent', 'theme', 'goal', 'location'],
'involve-107.1':              ['agent', 'theme', 'goal', 'location'],
'body_motion-49.2':           ['agent', 'theme', 'goal', 'path', 'location'],
'body_motion-49.2-1':         ['agent', 'theme', 'goal', 'path', 'location'],
'push-12-1-1':                ['agent', 'theme', 'goal', 'source', 'trajectory', 'location'],
'wipe_instr-10.4.2':          ['agent', 'theme', 'initial_location', 'destination', 'instrument', 'result', 'location'],
'pour-9.5':                   ['agent', 'theme', 'initial_location', 'destination', 'location'],
'wipe_instr-10.4.2-1':        ['agent', 'theme', 'initial_location', 'destination', 'location'],
'chase-51.6':                 ['agent', 'theme', 'initial_location', 'destination', 'trajectory', 'location'],
'vehicle_path-51.4.3':        ['agent', 'theme', 'initial_location', 'destination', 'trajectory', 'location'],
'distinguish-23.5':           ['agent', 'theme', 'instrument', 'co_theme', 'location'],
'distinguish-23.5-1':         ['agent', 'theme', 'instrument', 'co_theme', 'location'],
'begin-55.1':                 ['agent', 'theme', 'instrument', 'location'],
'begin-55.1-1-1':             ['agent', 'theme', 'instrument', 'location'],
'confront-98':                ['agent', 'theme', 'instrument', 'location'],
'establish-55.5-1':           ['agent', 'theme', 'instrument', 'location'],
'satisfy-55.7':               ['agent', 'theme', 'instrument', 'location'],
'support-15.3':               ['agent', 'theme', 'instrument', 'location'],
'support-15.3-1':             ['agent', 'theme', 'instrument', 'location'],
'sustain-55.6':               ['agent', 'theme', 'instrument', 'location'],
'accept-77.1':                ['agent', 'theme', 'location'],
'admit-64.3':                 ['agent', 'theme', 'location'],
'admit-64.3-1':               ['agent', 'theme', 'location'],
'adopt-93':                   ['agent', 'theme', 'location'],
'begin-55.1-1':               ['agent', 'theme', 'location'],
'being_dressed-41.3.3':       ['agent', 'theme', 'location'],
'breathe-40.1.2-1':           ['agent', 'theme', 'location'],
'caring-75.2':                ['agent', 'theme', 'location'],
'caring-75.2-1':              ['agent', 'theme', 'location'],
'caring-75.2-1-1':            ['agent', 'theme', 'location'],
'caring-75.2-2':              ['agent', 'theme', 'location'],
'complete-55.2':              ['agent', 'theme', 'location'],
'complete-55.2-1':            ['agent', 'theme', 'location'],
'cope-83':                    ['agent', 'theme', 'location'],
'cope-83-1':                  ['agent', 'theme', 'location'],
'cope-83-1-1':                ['agent', 'theme', 'location'],
'declare-29.4-1-1':           ['agent', 'theme', 'location'],
'declare-29.4-1-1-1':         ['agent', 'theme', 'location'],
'declare-29.4-1-1-2':         ['agent', 'theme', 'location'],
'declare-29.4-1-1-3':         ['agent', 'theme', 'location'],
'declare-29.4-2':             ['agent', 'theme', 'location'],
'enforce-63':                 ['agent', 'theme', 'location'],
'establish-55.5':             ['agent', 'theme', 'location'],
'hold-15.1':                  ['agent', 'theme', 'location'],
'hunt-35.1':                  ['agent', 'theme', 'location'],
'investigate-35.4':           ['agent', 'theme', 'location'],
'keep-15.2':                  ['agent', 'theme', 'location'],
'light_emission-43.1':        ['agent', 'theme', 'location'],
'linger-53.1':                ['agent', 'theme', 'location'],
'linger-53.1-1':              ['agent', 'theme', 'location'],
'modes_of_being_with_motion-47.3': ['agent', 'theme', 'location'],
'neglect-75.1':               ['agent', 'theme', 'location'],
'neglect-75.1-1':             ['agent', 'theme', 'location'],
'orphan-29.7':                ['agent', 'theme', 'location'],
'patent-101':                 ['agent', 'theme', 'location'],
'peer-30.3':                  ['agent', 'theme', 'location'],
'promote-102':                ['agent', 'theme', 'location'],
'push-12':                    ['agent', 'theme', 'location'],
'refrain-69':                 ['agent', 'theme', 'location'],
'rehearse-26.8':              ['agent', 'theme', 'location'],
'rehearse-26.8-1':            ['agent', 'theme', 'location'],
'reject-77.2':                ['agent', 'theme', 'location'],
'reject-77.2-1':              ['agent', 'theme', 'location'],
'rely-70':                    ['agent', 'theme', 'location'],
'risk-94':                    ['agent', 'theme', 'location'],
'risk-94-1':                  ['agent', 'theme', 'location'],
'rummage-35.5':               ['agent', 'theme', 'location'],
'rummage-35.5-1':             ['agent', 'theme', 'location'],
'rush-53.2':                  ['agent', 'theme', 'location'],
'search-35.2':                ['agent', 'theme', 'location'],
'simple_dressing-41.3.1':     ['agent', 'theme', 'location'],
'snooze-40.4-1':              ['agent', 'theme', 'location'],
'sound_emission-43.2':        ['agent', 'theme', 'location'],
'spatial_configuration-47.6-1': ['agent', 'theme', 'location'],
'stalk-35.3':                 ['agent', 'theme', 'location'],
'stop-55.4-1-1':              ['agent', 'theme', 'location'],
'succeed-74':                 ['agent', 'theme', 'location'],
'succeed-74-1':               ['agent', 'theme', 'location'],
'succeed-74-1-1':             ['agent', 'theme', 'location'],
'succeed-74-2':               ['agent', 'theme', 'location'],
'succeed-74-3':               ['agent', 'theme', 'location'],
'succeed-74-3-1':             ['agent', 'theme', 'location'],
'succeed-74-3-1-1':           ['agent', 'theme', 'location'],
'trifle-105.3':               ['agent', 'theme', 'location'],
'try-61.1':                   ['agent', 'theme', 'location'],
'vehicle-51.4.1-1':           ['agent', 'theme', 'location'],
'body_motion-49.2-1-1':       ['agent', 'theme', 'path', 'location'],
'volunteer-95.4':             ['agent', 'pivot', 'theme', 'location'],
'conjecture-29.5':            ['agent', 'theme', 'predicate', 'location'],
'conjecture-29.5-1':          ['agent', 'theme', 'predicate', 'location'],
'conjecture-29.5-2':          ['agent', 'theme', 'predicate', 'location'],
'reciprocate-112':            ['agent', 'theme', 'predicate', 'location'],
'reciprocate-112-1':          ['agent', 'theme', 'predicate', 'location'],
'respond-113':                ['agent', 'theme', 'predicate', 'location'],
'use-105.1':                  ['agent', 'theme', 'predicate', 'location'],
'coil-9.6-1':                 ['agent', 'theme', 'prop', 'location'],
'feeding-39.7':               ['agent', 'theme', 'recipient', 'location'],
'reflexive_appearance-48.1.2': ['agent', 'theme', 'recipient', 'location'],
'appoint-29.1':               ['agent', 'theme', 'result', 'location'],
'declare-29.4':               ['agent', 'theme', 'result', 'location'],
'declare-29.4-1':             ['agent', 'theme', 'result', 'location'],
'dub-29.3.2':                 ['agent', 'theme', 'result', 'location'],
'push-12-1':                  ['agent', 'theme', 'result', 'location'],
'banish-10.2':                ['agent', 'theme', 'source', 'destination', 'location'],
'clear-10.3':                 ['agent', 'theme', 'source', 'destination', 'location'],
'clear-10.3-1':               ['agent', 'theme', 'source', 'destination', 'location'],
'debone-10.8':                ['agent', 'theme', 'source', 'destination', 'location'],
'wipe_manner-10.4.1':         ['agent', 'theme', 'source', 'destination', 'location'],
'fire-10.10':                 ['agent', 'theme', 'source', 'goal', 'attribute', 'location'],
'remove-10.1':                ['agent', 'theme', 'source', 'goal', 'location'],
'base-97.1':                  ['agent', 'theme', 'source', 'location'],
'deduce-97.2':                ['agent', 'theme', 'source', 'location'],
'discover-84':                ['agent', 'theme', 'source', 'location'],
'discover-84-1':              ['agent', 'theme', 'source', 'location'],
'discover-84-1-1':            ['agent', 'theme', 'source', 'location'],
'ferret-35.6':                ['agent', 'theme', 'source', 'location'],
'wipe_manner-10.4.1-1':       ['agent', 'theme', 'source', 'location'],
'estimate-34.2':              ['agent', 'theme', 'value', 'location'],
'estimate-34.2-1':            ['agent', 'theme', 'value', 'location'],
'price-54.4':                 ['agent', 'theme', 'value', 'location'],
'bring-11.3-1':               ['agent', 'theme', ['destination', 'co_theme'], 'location'],
'roll-51.3.1':                ['agent', 'theme', ['destination', 'result'], ['initial_location', 'source'], 'trajectory', 'location'],
'run-51.3.2-2':               ['agent', 'theme', ['destination', 'result'], ['initial_location', 'source'], 'trajectory', 'location'],
'vehicle-51.4.1':             ['agent', 'theme', ['destination', 'result'], ['initial_location', 'source'], 'trajectory', 'location'],
'continue-55.3':              ['agent', 'theme', ['final_time', 'time'], 'location'],
'waltz-51.5':                 ['agent', 'theme', ['initial_location', 'source'], 'goal', 'trajectory', 'location'],
'mine-10.9':                  ['agent', 'theme', 'initial_location', 'destination', 'location'],
'intend-61.2':                ['agent', 'topic', 'attribute', 'location'],
'focus-87.1':                 ['agent', 'topic', 'location'],
'focus-87.1-1':               ['agent', 'topic', 'location'],
'intend-61.2-1':              ['agent', 'topic', 'location'],
'intend-61.2-1-1':            ['agent', 'topic', 'location'],
'fit-54.3':                   ['agent', 'value', 'goal', 'location'],
'poke-19':                    ['agent', ['patient', 'destination'], 'instrument', 'location'],
'addict-96':                  ['agent', ['patient', 'experiencer'], 'stimulus', 'location'],
'acquiesce-95.1':             ['agent', ['theme', 'co_agent'], 'location'],
'acquiesce-95.1-1':           ['agent', ['theme', 'co_agent'], 'location'],
'invest-13.5.4':              ['agent', ['theme', 'goal'], 'asset', 'location'],
'invest-13.5.4-1':            ['agent', ['theme', 'goal'], 'asset', 'location'],
'avoid-52':                   ['agent', 'theme', 'location'],
'benefit-72.2':               ['beneficiary', 'causer', 'location'],
'cost-54.2':                  ['beneficiary', 'theme', 'value', 'location'],
'caused_calibratable_cos-45.6.2': ['causer', 'patient', 'attribute', 'extent', 'source', 'goal', 'location'],
'limit-76':                   ['causer', 'patient', 'goal', 'location'],
'indicate-78':                ['causer', 'recipient', 'topic', 'location'],
'indicate-78-1':              ['causer', 'recipient', 'topic', 'location'],
'indicate-78-1-1':            ['causer', 'recipient', 'topic', 'location'],
'free-10.6.3':                ['causer', 'source', 'theme', 'location'],
'free-10.6.3-1':              ['causer', 'source', 'theme', 'location'],
'free-10.6.3-1-1':            ['causer', 'source', 'theme', 'location'],
'engender-27.1':              ['causer', 'theme', 'location'],
'engender-27.1-1':            ['causer', 'theme', 'location'],
'result-27.2':                ['causer', 'theme', 'location'],
'hurt-40.8.3':                ['experiencer', 'patient', 'location'],
'hurt-40.8.3-1':              ['experiencer', 'patient', 'location'],
'hurt-40.8.3-1-1':            ['experiencer', 'patient', 'location'],
'hurt-40.8.3-2':              ['experiencer', 'patient', 'location'],
'pain-40.8.1':                ['experiencer', 'patient', 'stimulus', 'location'],
'tingle-40.8.2':              ['experiencer', 'patient', 'stimulus', 'location'],
'admire-31.2':                ['experiencer', 'stimulus', 'attribute', 'location'],
'comprehend-87.2':            ['experiencer', 'stimulus', 'attribute', 'location'],
'comprehend-87.2-1':          ['experiencer', 'stimulus', 'attribute', 'location'],
'admire-31.2-1':              ['experiencer', 'stimulus', 'location'],
'appeal-31.4':                ['experiencer', 'stimulus', 'location'],
'appeal-31.4-1':              ['experiencer', 'stimulus', 'location'],
'appeal-31.4-2':              ['experiencer', 'stimulus', 'location'],
'appeal-31.4-3':              ['experiencer', 'stimulus', 'location'],
'body_internal_states-40.6':  ['experiencer', 'stimulus', 'location'],
'care-88.1':                  ['experiencer', 'stimulus', 'emotion', 'location'],
'care-88.1-1':                ['experiencer', 'stimulus', 'emotion', 'location'],
'change_bodily_state-40.8.4': ['experiencer', 'stimulus', 'final_state', 'location'],
'cognize-85':                 ['experiencer', 'stimulus', 'location'],
'comprehend-87.2-1-1':        ['experiencer', 'stimulus', 'location'],
'comprehend-87.2-1-1-1':      ['experiencer', 'stimulus', 'location'],
'empathize-88.2':             ['experiencer', 'stimulus', 'location'],
'encounter-30.5':             ['experiencer', 'stimulus', 'location'],
'flinch-40.5':                ['experiencer', 'stimulus', 'position', 'location'],
'marvel-31.3':                ['experiencer', 'stimulus', 'emotion', 'location'],
'matter-91':                  ['experiencer', 'stimulus', 'location'],
'see-30.1':                   ['experiencer', 'stimulus', 'location'],
'see-30.1-1':                 ['experiencer', 'stimulus', 'location'],
'see-30.1-1-1':               ['experiencer', 'stimulus', 'location'],
'see-30.1-1-1-1':             ['experiencer', 'stimulus', 'location'],
'sight-30.2':                 ['experiencer', 'stimulus', 'location'],
'stimulus_subject-30.4':      ['experiencer', 'stimulus', 'location'],
'wish-62':                    ['experiencer', 'stimulus', 'location'],
'bulge-47.5.3':               [['agent', 'destination'], 'theme', 'location'],
'calibratable_cos-45.6.1':    ['patient', 'attribute', 'extent', 'initial_state', 'result', 'location'],
'calibratable_cos-45.6.1-1':  ['patient', 'attribute', 'extent', 'initial_state', 'result', 'location'],
'die-42.4':                   ['patient', 'causer', 'location'],
'die-42.4-1':                 ['patient', 'causer', 'location'],
'caused_calibratable_cos-45.6.2-1': ['patient', 'extent', 'source', 'goal', 'attribute', 'direction', 'location'],
'disappearance-48.2':         ['theme', 'initial_location', 'location'],
'disappearance-48.2-1':       ['theme', 'initial_location', 'location'],
'entity_specific_cos-45.5':   ['patient', 'final_state', 'location'],
'break_down-45.8':            ['patient', 'location'],
'convert-26.6.2':             ['patient', 'result', 'initial_state', 'location'],
'convert-26.6.2-1':           ['patient', 'result', 'initial_state', 'location'],
'become-109.1':               ['patient', 'result', 'location'],
'become-109.1-1':             ['patient', 'result', 'location'],
'become-109.1-1-1':           ['patient', 'result', 'location'],
'contain-15.4':               ['pivot', 'theme', 'location'],
'exhale-40.1.3':              ['pivot', 'theme', 'location'],
'exhale-40.1.3-1':            ['pivot', 'theme', 'location'],
'exhale-40.1.3-2':            ['pivot', 'theme', 'location'],
'long-32.2':                  ['pivot', 'theme', 'location'],
'long-32.2-1':                ['pivot', 'theme', 'location'],
'long-32.2-2':                ['pivot', 'theme', 'location'],
'own-100.1':                  ['pivot', 'theme', 'location'],
'want-32.1':                  ['pivot', 'theme', 'location'],
'want-32.1-1':                ['pivot', 'theme', 'location'],
'want-32.1-1-1':              ['pivot', 'theme', 'location'],
'require-103':                ['pivot', 'theme', 'source', 'location'],
'require-103-1':              ['pivot', 'theme', 'source', 'location'],
'require-103-2':              ['pivot', 'theme', 'source', 'location'],
'ensure-99':                  ['precondition', 'theme', 'beneficiary', 'location'],
'equip-13.4.2-1-1':           ['recipient', 'theme', 'location'],
'substance_emission-43.4':    ['source', 'theme', 'location'],
'substance_emission-43.4-1':  ['source', 'theme', 'location'],
'amuse-31.1':                 ['stimulus', 'experiencer', 'location'],
'earn-54.6':                  ['theme', 'asset', 'location'],
'comprise-107.2':             ['theme', 'attribute', 'location'],
'comprise-107.2-1':           ['theme', 'attribute', 'location'],
'seem-109':                   ['theme', 'attribute', 'location'],
'seem-109-1':                 ['theme', 'attribute', 'location'],
'seem-109-1-1':               ['theme', 'attribute', 'location'],
'seem-109-1-1-1':             ['theme', 'attribute', 'location'],
'exceed-90':                  ['theme', 'co_theme', 'attribute', 'location'],
'representation-110.1':       ['theme', 'co_theme', 'context', 'location'],
'bump-18.4':                  ['theme', 'co_theme', 'location'],
'bump-18.4-1':                ['theme', 'co_theme', 'location'],
'cling-22.5':                 ['theme', 'co_theme', 'location'],
'contiguous_location-47.8':   ['theme', 'co_theme', 'location'],
'contiguous_location-47.8-1': ['theme', 'co_theme', 'location'],
'contiguous_location-47.8-2': ['theme', 'co_theme', 'location'],
'differ-23.4':                ['theme', 'co_theme', 'location'],
'harmonize-22.6':             ['theme', 'co_theme', 'location'],
'relate-86.2':                ['theme', 'co_theme', 'location'],
'relate-86.2-1':              ['theme', 'co_theme', 'location'],
'relate-86.2-2':              ['theme', 'co_theme', 'location'],
'substitute-13.6.2':          ['theme', 'co_theme', ['source', 'co_goal'], ['co_source', 'goal'], ['location']],
'substitute-13.6.2-1':        ['theme', 'co_theme', ['source', 'goal'], ['co_source', 'co_goal'], ['location']],
'escape-51.1-1-2':            ['theme', 'destination', 'initial_location', 'trajectory', 'location'],
'nonvehicle-51.4.2-1':        ['theme', 'destination', 'initial_location', 'trajectory', 'location'],
'run-51.3.2':                 ['theme', 'destination', 'initial_location', 'trajectory', 'location'],
'run-51.3.2-1':               ['theme', 'destination', 'initial_location', 'trajectory', 'location'],
'rotate-51.9.1':              ['theme', 'extent', 'initial_location', 'trajectory', 'location'],
'attend-107.4':               ['theme', 'goal', 'location'],
'attend-107.4-1':             ['theme', 'goal', 'location'],
'attend-107.4-2':             ['theme', 'goal', 'location'],
'reach-51.8':                 ['theme', 'goal', 'source', 'trajectory', 'location'],
'escape-51.1':                ['theme', 'initial_location', 'destination', 'trajectory', 'location'],
'escape-51.1-1':              ['theme', 'initial_location', 'destination', 'trajectory', 'location'],
'escape-51.1-1-1':            ['theme', 'initial_location', 'destination', 'trajectory', 'location'],
'appear-48.1.1':              ['theme', 'location'],
'disfunction-105.2.2':        ['theme', 'location'],
'entity_specific_modes_being-47.2': ['theme', 'location'],
'exist-47.1':                 ['theme', 'location'],
'function-105.2.1':           ['theme', 'location'],
'lodge-46':                   ['theme', 'location'],
'meander-47.7':               ['theme', 'location'],
'meander-47.7-1':             ['theme', 'location'],
'occur-48.3':                 ['theme', 'location'],
'occur-48.3-1':               ['theme', 'location'],
'occur-48.3-2':               ['theme', 'location'],
'smell_emission-43.3':        ['theme', 'location'],
'sound_existence-47.4':       ['theme', 'location'],
'stop-55.4-1':                ['theme', 'location'],
'swarm-47.5.1':               ['theme', 'location'],
'swarm-47.5.1-1':             ['theme', 'location'],
'swarm-47.5.1-2':             ['theme', 'location'],
'swarm-47.5.1-2-1':           ['theme', 'location'],
#
'terminus-47.9':              ['theme', 'destination', 'location'],
#
'weather-57':                 ['theme', 'location'],
'weekend-56':                 ['theme', 'location'],
'spatial_configuration-47.6': ['theme', 'pos', 'location'],
'function-105.2.1-1':         ['theme', 'predicate', 'location'],
'leave-51.2':                 ['theme', 'source', 'goal', 'trajectory', 'location'],
'leave-51.2-1':               ['theme', 'source', 'goal', 'trajectory', 'location'],
'escape-51.1-1-3':            ['theme', 'trajectory', 'destination', 'initial_location', 'location'],
'register-54.1':              ['theme', 'value', 'location'],
'register-54.1-1-1':          ['theme', 'value', 'location'],
'exist-47.1-1':               ['theme', ['pivot', 'manner'], 'location'],
'rob-10.6.4':                 [['agent', 'beneficiary'], 'theme', 'source', 'location'],
'steal-10.5':                 [['agent', 'beneficiary'], 'theme', 'source', 'location'],
'steal-10.5-1':               [['agent', 'beneficiary'], 'theme', 'source', 'location'],
'render-29.90':               [['agent', 'causer'], 'patient', 'result', 'source', 'location'],
'throw-17.1-1-1':             [['agent', 'causer'], 'theme', 'result', 'location'],
'exchange-13.6.1':            [['agent', 'co_goal', 'source'], ['co_agent', 'goal', 'co_source'], 'theme', 'co_theme', 'location'],
'talk-37.5':                  [['agent', 'co_recipient', 'source'], ['co_agent', 'co_source', 'recipient'], 'topic', 'location'],
'get-13.5.1':                 [['agent', 'goal'], 'theme', 'beneficiary', 'source', 'asset', 'location'],
'absorb-39.8':                [['agent', 'goal'], 'theme', 'source', 'location'],
'cheat-10.6.1':               [['agent', 'goal'], 'theme', 'source', 'location'],
'cheat-10.6.1-1':             [['agent', 'goal'], 'theme', 'source', 'location'],
'cheat-10.6.1-1-1':           [['agent', 'goal'], 'theme', 'source', 'location'],
'deprive-10.6.2':             [['agent', 'goal'], 'theme', 'source', 'location'],
'get-13.5.1-1':               [['agent', 'goal'], 'theme', 'source', 'location'],
'learn-14':                   [['agent', 'goal'], 'topic', ['recipient', 'source'], 'location'],
'learn-14-1':                 [['agent', 'goal'], 'topic', ['recipient', 'source'], 'location'],
'learn-14-2':                 [['agent', 'goal'], 'topic', ['recipient', 'source'], 'location'],
'learn-14-2-1':               [['agent', 'goal'], 'topic', ['recipient', 'source'], 'location'],
'interrogate-37.1.3':         [['agent', 'goal'], ['recipient', 'source'], 'topic', 'attribute', 'location'],
'inquire-37.1.2':             [['agent', 'goal'], ['recipient', 'source'], 'topic', 'location'],
'throw-17.1':                 [['agent', 'initial_location'], 'theme', 'destination', 'location'],
'throw-17.1-1':               [['agent', 'initial_location'], 'theme', 'destination', 'location'],
'bring-11.3':                 [['agent', 'instrument'], 'theme', 'destination', 'initial_location', 'location'],
'obtain-13.5.2-1':            [['agent', 'recipient'], 'theme', 'source', 'asset', 'location'],
'berry-13.7':                 [['agent', 'recipient'], 'theme', 'source', 'location'],
'obtain-13.5.2':              [['agent', 'recipient'], 'theme', 'source', 'location'],
'chit_chat-37.6':             [['agent', 'source', 'co_recipient'], ['co_agent', 'recipient', 'co_source'], 'topic', 'location'],
'chit_chat-37.6-1':           [['agent', 'source', 'co_recipient'], ['co_agent', 'recipient', 'co_source'], 'topic', 'location'],
'consume-66':                 [['agent', 'source'], 'asset', 'goal', 'location'],
'consume-66-1':               [['agent', 'source'], 'asset', 'goal', 'location'],
'wink-40.3.1':                [['agent', 'source'], 'patient', 'recipient', 'theme', 'location'],
'crane-40.3.2':               [['agent', 'source'], 'patient', 'recipient', 'topic', 'location'],
'contribute-13.2':            [['agent', 'source'], 'recipient', 'theme', 'location'],
'contribute-13.2-1':          [['agent', 'source'], 'recipient', 'theme', 'location'],
'contribute-13.2-1-1':        [['agent', 'source'], 'recipient', 'theme', 'location'],
'contribute-13.2-2':          [['agent', 'source'], 'recipient', 'theme', 'location'],
'contribute-13.2-2-1':        [['agent', 'source'], 'recipient', 'theme', 'location'],
'equip-13.4.2':               [['agent', 'source'], 'recipient', 'theme', 'location'],
'equip-13.4.2-1':             [['agent', 'source'], 'recipient', 'theme', 'location'],
'nonverbal_expression-40.2':  [['agent', 'source'], 'recipient', 'theme', 'location'],
'advise-37.9':                [['agent', 'source'], 'recipient', 'topic', 'location'],
'advise-37.9-1':              [['agent', 'source'], 'recipient', 'topic', 'location'],
'complain-37.8':              [['agent', 'source'], 'recipient', 'topic', 'location'],
'confess-37.10':              [['agent', 'source'], 'recipient', 'topic', 'location'],
'curtsey-40.3.3':             [['agent', 'source'], 'recipient', 'topic', 'location'],
'initiate_communication-37.4.2': [['agent', 'source'], 'recipient', 'topic', 'location'],
'initiate_communication-37.4.2-1': [['agent', 'source'], 'recipient', 'topic', 'location'],
'promise-37.13':              [['agent', 'source'], 'recipient', 'topic', 'location'],
'transfer_mesg-37.1.1':       [['agent', 'source'], 'recipient', 'topic', 'location'],
'transfer_mesg-37.1.1-1':     [['agent', 'source'], 'recipient', 'topic', 'location'],
'transfer_mesg-37.1.1-1-1':   [['agent', 'source'], 'recipient', 'topic', 'location'],
'pay-68':                     [['agent', 'source'], 'theme', 'asset', 'recipient', 'location'],
'pay-68-1':                   [['agent', 'source'], 'theme', 'asset', 'recipient', 'location'],
'breathe-40.1.2':             [['agent', 'source'], 'theme', 'destination', 'location'],
'give-13.1-1':                [['agent', 'source'], 'theme', 'recipient', 'asset', 'location'],
'fulfilling-13.4.1':          [['agent', 'source'], 'theme', 'recipient', 'location'],
'fulfilling-13.4.1-1':        [['agent', 'source'], 'theme', 'recipient', 'location'],
'fulfilling-13.4.1-2':        [['agent', 'source'], 'theme', 'recipient', 'location'],
'give-13.1':                  [['agent', 'source'], 'theme', 'recipient', 'location'],
'future_having-13.3':         [['agent', 'source'], 'theme', ['beneficiary', 'goal'], 'location'],
'instr_communication-37.4.1': [['agent', 'source'], 'topic', 'recipient', 'location'],
'lecture-37.11':              [['agent', 'source'], 'topic', 'recipient', 'location'],
'lecture-37.11-1':            [['agent', 'source'], 'topic', 'recipient', 'location'],
'lecture-37.11-1-1':          [['agent', 'source'], 'topic', 'recipient', 'location'],
'lecture-37.11-2':            [['agent', 'source'], 'topic', 'recipient', 'location'],
'manner_speaking-37.3':       [['agent', 'source'], 'topic', 'recipient', 'manner', 'location'],
'say-37.7':                   [['agent', 'source'], 'topic', 'recipient', 'location'],
'say-37.7-1':                 [['agent', 'source'], 'topic', 'recipient', 'location'],
'say-37.7-1-1':               [['agent', 'source'], 'topic', 'recipient', 'location'],
'say-37.7-1-1-1':             [['agent', 'source'], 'topic', 'recipient', 'location'],
'say-37.7-1-2':               [['agent', 'source'], 'topic', 'recipient', 'location'],
'tell-37.2':                  [['agent', 'source'], 'topic', 'recipient', 'location'],
'overstate-37.12':            [['agent', 'source'], ['theme', 'topic'], 'recipient', 'location'],
'orbit-51.9.2':               [['theme', 'axis'], ['destination', 'initial_location'], 'trajectory', 'location']
}
